/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/music` | `/music`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/playlists` | `/playlists`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/videos` | `/videos`; params?: Router.UnknownInputParams; } | { pathname: `/player/audio`; params?: Router.UnknownInputParams; } | { pathname: `/player/video`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/music` | `/music`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/playlists` | `/playlists`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/videos` | `/videos`; params?: Router.UnknownOutputParams; } | { pathname: `/player/audio`; params?: Router.UnknownOutputParams; } | { pathname: `/player/video`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/music${`?${string}` | `#${string}` | ''}` | `/music${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/playlists${`?${string}` | `#${string}` | ''}` | `/playlists${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/videos${`?${string}` | `#${string}` | ''}` | `/videos${`?${string}` | `#${string}` | ''}` | `/player/audio${`?${string}` | `#${string}` | ''}` | `/player/video${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/music` | `/music`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/playlists` | `/playlists`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/videos` | `/videos`; params?: Router.UnknownInputParams; } | { pathname: `/player/audio`; params?: Router.UnknownInputParams; } | { pathname: `/player/video`; params?: Router.UnknownInputParams; };
    }
  }
}
